import cat from "./images/cat1.jpg"
import cat1 from "./images/cat2.jpg"

export const data = [
    {
        id:1,
        catName:"Boots",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:2,
        catName:"Kiddos",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat1
    },
    {
        id:3,
        catName:"Loona",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:4,
        catName:"Ricky",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:5,
        catName:"Tabby",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:6,
        catName:"Tiger",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:7,
        catName:"Loona2",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:8,
        catName:"Boots2",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:9,
        catName:"Ricky2",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:10,
        catName:"Boots5",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:11,
        catName:"Boots6",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:12,
        catName:"Boots7",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:13,
        catName:"Boots10",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:14,
        catName:"Tiger5",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:15,
        catName:"Tiger10",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },
    {
        id:16,
        catName:"Kitty",
        nicNames:["taby,toby,tubbibi"],
        age:"28",
        image:cat
    },

]